ALTER TABLE clinics
ADD COLUMN IF NOT EXISTS display_name VARCHAR(255),
ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE users
ADD COLUMN IF NOT EXISTS clinic_id INT,
ADD COLUMN IF NOT EXISTS email VARCHAR(320),
ADD COLUMN IF NOT EXISTS password_hash TEXT,
ADD COLUMN IF NOT EXISTS user_role_label VARCHAR(100),
ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE clinic_settings
ADD COLUMN IF NOT EXISTS timezone VARCHAR(100),
ADD COLUMN IF NOT EXISTS default_channel_type VARCHAR(50),
ADD COLUMN IF NOT EXISTS appointment_reminder_hours_before INT,
ADD COLUMN IF NOT EXISTS follow_up_delay_days INT,
ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP;

CREATE TABLE IF NOT EXISTS specializations (
  specialization_id SERIAL PRIMARY KEY,
  clinic_id INT NOT NULL REFERENCES clinics(clinic_id) ON DELETE CASCADE,
  display_name VARCHAR(255) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE specializations
ADD COLUMN IF NOT EXISTS clinic_id INT,
ADD COLUMN IF NOT EXISTS display_name VARCHAR(255),
ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP;

CREATE TABLE IF NOT EXISTS doctors (
  doctor_id SERIAL PRIMARY KEY,
  clinic_id INT NOT NULL REFERENCES clinics(clinic_id) ON DELETE CASCADE,
  display_name VARCHAR(255) NOT NULL,
  specialization_id INT NOT NULL REFERENCES specializations(specialization_id) ON DELETE RESTRICT,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE doctors
ADD COLUMN IF NOT EXISTS clinic_id INT,
ADD COLUMN IF NOT EXISTS display_name VARCHAR(255),
ADD COLUMN IF NOT EXISTS specialization_id INT,
ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP;

CREATE TABLE IF NOT EXISTS patients (
  patient_id SERIAL PRIMARY KEY,
  clinic_id INT NOT NULL REFERENCES clinics(clinic_id) ON DELETE CASCADE,
  display_name VARCHAR(255) NOT NULL,
  cnp VARCHAR(13),
  sex VARCHAR(20),
  birth_date DATE,
  city VARCHAR(255),
  phone_number VARCHAR(32) NOT NULL,
  email VARCHAR(320),
  notes TEXT,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE patients
ADD COLUMN IF NOT EXISTS clinic_id INT,
ADD COLUMN IF NOT EXISTS display_name VARCHAR(255),
ADD COLUMN IF NOT EXISTS cnp VARCHAR(13),
ADD COLUMN IF NOT EXISTS sex VARCHAR(20),
ADD COLUMN IF NOT EXISTS birth_date DATE,
ADD COLUMN IF NOT EXISTS city VARCHAR(255),
ADD COLUMN IF NOT EXISTS phone_number VARCHAR(32),
ADD COLUMN IF NOT EXISTS email VARCHAR(320),
ADD COLUMN IF NOT EXISTS notes TEXT,
ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP;

CREATE TABLE IF NOT EXISTS appointments (
  appointment_id SERIAL PRIMARY KEY,
  clinic_id INT NOT NULL REFERENCES clinics(clinic_id) ON DELETE CASCADE,
  doctor_id INT NOT NULL REFERENCES doctors(doctor_id) ON DELETE RESTRICT,
  patient_id INT NOT NULL REFERENCES patients(patient_id) ON DELETE RESTRICT,
  start_date_time TIMESTAMPTZ NOT NULL,
  end_date_time TIMESTAMPTZ NOT NULL,
  appointment_notes TEXT,
  appointment_status VARCHAR(100) NOT NULL,
  confirmation_status VARCHAR(100) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE appointments
ADD COLUMN IF NOT EXISTS clinic_id INT,
ADD COLUMN IF NOT EXISTS doctor_id INT,
ADD COLUMN IF NOT EXISTS patient_id INT,
ADD COLUMN IF NOT EXISTS start_date_time TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS end_date_time TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS appointment_notes TEXT,
ADD COLUMN IF NOT EXISTS appointment_status VARCHAR(100),
ADD COLUMN IF NOT EXISTS confirmation_status VARCHAR(100),
ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP;

CREATE TABLE IF NOT EXISTS messages (
  message_id SERIAL PRIMARY KEY,
  clinic_id INT NOT NULL REFERENCES clinics(clinic_id) ON DELETE CASCADE,
  appointment_id INT NOT NULL REFERENCES appointments(appointment_id) ON DELETE CASCADE,
  channel_type VARCHAR(50) NOT NULL,
  message_subject VARCHAR(255) NOT NULL,
  message_body TEXT NOT NULL,
  message_status VARCHAR(100) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE messages
ADD COLUMN IF NOT EXISTS clinic_id INT,
ADD COLUMN IF NOT EXISTS appointment_id INT,
ADD COLUMN IF NOT EXISTS channel_type VARCHAR(50),
ADD COLUMN IF NOT EXISTS message_subject VARCHAR(255),
ADD COLUMN IF NOT EXISTS message_body TEXT,
ADD COLUMN IF NOT EXISTS message_status VARCHAR(100),
ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP;

CREATE TABLE IF NOT EXISTS follow_ups (
  follow_up_id SERIAL PRIMARY KEY,
  clinic_id INT NOT NULL REFERENCES clinics(clinic_id) ON DELETE CASCADE,
  appointment_id INT NOT NULL REFERENCES appointments(appointment_id) ON DELETE CASCADE,
  follow_up_status VARCHAR(100) NOT NULL,
  scheduled_for TIMESTAMPTZ NOT NULL,
  follow_up_notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE follow_ups
ADD COLUMN IF NOT EXISTS clinic_id INT,
ADD COLUMN IF NOT EXISTS appointment_id INT,
ADD COLUMN IF NOT EXISTS follow_up_status VARCHAR(100),
ADD COLUMN IF NOT EXISTS scheduled_for TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS follow_up_notes TEXT,
ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP;

CREATE TABLE IF NOT EXISTS message_templates (
  template_id SERIAL PRIMARY KEY,
  clinic_id INT NOT NULL REFERENCES clinics(clinic_id) ON DELETE CASCADE,
  template_name VARCHAR(255) NOT NULL,
  channel_type VARCHAR(50) NOT NULL,
  message_subject VARCHAR(255) NOT NULL,
  message_body TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE message_templates
ADD COLUMN IF NOT EXISTS clinic_id INT,
ADD COLUMN IF NOT EXISTS template_name VARCHAR(255),
ADD COLUMN IF NOT EXISTS channel_type VARCHAR(50),
ADD COLUMN IF NOT EXISTS message_subject VARCHAR(255),
ADD COLUMN IF NOT EXISTS message_body TEXT,
ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP;

CREATE TABLE IF NOT EXISTS responses (
  response_id SERIAL PRIMARY KEY,
  clinic_id INT NOT NULL REFERENCES clinics(clinic_id) ON DELETE CASCADE,
  message_id INT NOT NULL REFERENCES messages(message_id) ON DELETE CASCADE,
  response_status VARCHAR(100) NOT NULL,
  response_text TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE responses
ADD COLUMN IF NOT EXISTS clinic_id INT,
ADD COLUMN IF NOT EXISTS message_id INT,
ADD COLUMN IF NOT EXISTS response_status VARCHAR(100),
ADD COLUMN IF NOT EXISTS response_text TEXT,
ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP;

CREATE TABLE IF NOT EXISTS imports (
  import_id SERIAL PRIMARY KEY,
  clinic_id INT NOT NULL REFERENCES clinics(clinic_id) ON DELETE CASCADE,
  imported_by_user_id INT NOT NULL REFERENCES users(user_id) ON DELETE RESTRICT,
  file_name VARCHAR(255) NOT NULL,
  file_type VARCHAR(20) NOT NULL,
  import_status VARCHAR(50) NOT NULL,
  imported_count INT NOT NULL DEFAULT 0,
  failed_count INT NOT NULL DEFAULT 0,
  error_details TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE imports
ADD COLUMN IF NOT EXISTS clinic_id INT,
ADD COLUMN IF NOT EXISTS imported_by_user_id INT,
ADD COLUMN IF NOT EXISTS file_name VARCHAR(255),
ADD COLUMN IF NOT EXISTS file_type VARCHAR(20),
ADD COLUMN IF NOT EXISTS import_status VARCHAR(50),
ADD COLUMN IF NOT EXISTS imported_count INT NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS failed_count INT NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS error_details TEXT,
ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP;

CREATE TABLE IF NOT EXISTS doctor_schedules (
  doctor_schedule_id BIGSERIAL PRIMARY KEY,
  clinic_id BIGINT NOT NULL REFERENCES clinics(clinic_id) ON DELETE CASCADE,
  doctor_id BIGINT NOT NULL REFERENCES doctors(doctor_id) ON DELETE CASCADE,
  weekday INT NOT NULL,
  start_time TIME NOT NULL,
  end_time TIME NOT NULL,
  appointment_duration_minutes INT NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT doctor_schedules_weekday_check CHECK (weekday BETWEEN 1 AND 7),
  CONSTRAINT doctor_schedules_valid_range CHECK (start_time < end_time),
  CONSTRAINT doctor_schedules_appointment_duration_minutes_check CHECK (appointment_duration_minutes > 0)
);

ALTER TABLE doctor_schedules
ADD COLUMN IF NOT EXISTS clinic_id BIGINT,
ADD COLUMN IF NOT EXISTS doctor_id BIGINT,
ADD COLUMN IF NOT EXISTS weekday INT,
ADD COLUMN IF NOT EXISTS start_time TIME,
ADD COLUMN IF NOT EXISTS end_time TIME,
ADD COLUMN IF NOT EXISTS appointment_duration_minutes INT,
ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP;

CREATE UNIQUE INDEX IF NOT EXISTS users_clinic_id_email_key ON users (clinic_id, email);
CREATE UNIQUE INDEX IF NOT EXISTS doctor_schedules_unique_day ON doctor_schedules (clinic_id, doctor_id, weekday);
CREATE INDEX IF NOT EXISTS doctor_schedules_doctor_id_idx ON doctor_schedules (doctor_id);